/////////////////////////////////////
// Cut scene for when they're idle //
/////////////////////////////////////


IF
	GlobalLT("#L_GIRomance","GLOBAL",6)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		SetGlobal("#L_GIIdle","GLOBAL",0)
		SetGlobalTimer("#L_GIActionTimer","GLOBAL",ONE_DAY)
		DisplayStringHead("%IMOEN_DV%",@2016) // ~During the lull in activity, Imoen glances over toward Garrick and smiles.~
		Wait(2)
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",5)
	GlobalLT("#L_GIRomance","GLOBAL",11)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		SetGlobal("#L_GIIdle","GLOBAL",0)
		SetGlobalTimer("#L_GIActionTimer","GLOBAL",ONE_DAY)
		DisplayStringHead("GARRICK",@2025) // ~During the lull in activity, Garrick and Imoen glance at each other and smile.~
		Wait(2)
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",10)
	GlobalLT("#L_GIRomance","GLOBAL",21)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		SetGlobal("#L_GIIdle","GLOBAL",0)
		SetGlobalTimer("#L_GIActionTimer","GLOBAL",TWO_DAYS)
		DisplayStringHead("GARRICK",@2035) // ~Garrick and Imoen walk along together hand-in-hand.
		Wait(2)
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",20)
	GlobalLT("#L_GIRomance","GLOBAL",36)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		SetGlobal("#L_GIIdle","GLOBAL",0)
		SetGlobalTimer("#L_GIActionTimer","GLOBAL",THREE_DAYS)
		DisplayStringHead("GARRICK",@2043) // ~Garrick takes advantage of the short break to give Imoen a soft kiss.
		Wait(2)
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",35)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		SetGlobal("#L_GIIdle","GLOBAL",0)
		SetGlobalTimer("#L_GIActionTimer","GLOBAL",FIFTY_DAYS)
		EndCutSceneMode()
END
