//////////////////////////////////////////
// Cut scenes for when they are camping //
//////////////////////////////////////////

IF
	GlobalGT("#L_GIRomance","GLOBAL",0)
	GloballT("#L_GIRomance","GLOBAL",6)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		SetGlobalTimer("#L_GIRestTimer","GLOBAL",ONE_DAY)
		DisplayStringHead("%IMOEN_DV%",@2028) // ~Nonchalantly wanders over toward the fire and sits next to Garrick.~
		Wait(5)
		EndCutSceneMode()
		RestParty()
END
