/////////////////////////////////////////////
// Cut scenes for when they are at the inn //
/////////////////////////////////////////////

IF
	GlobalLT("#L_GIRomance","GLOBAL",6)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2012) // ~Listens intently, sighing softly~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",5)
	GlobalLT("#L_GIRomance","GLOBAL",11)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2021) // ~Imoen smiles broadly, obviously enjoying the attention.~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",10)
	GlobalLT("#L_GIRomance","GLOBAL",21)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2031) // ~Imoen smiles dreamily and sighs.~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",20)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		EndCutSceneMode()
END
