/////////////////////////////////////////////
// Cut scenes for when they are at the inn //
/////////////////////////////////////////////

IF
	GlobalLT("#L_GIRomance","GLOBAL",6)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2012) // ~Listens intently, sighing softly~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",5)
	GlobalLT("#L_GIRomance","GLOBAL",11)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2021) // ~Imoen smiles broadly, obviously enjoying the attention.~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",10)
	GlobalLT("#L_GIRomance","GLOBAL",21)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2031) // ~Imoen smiles dreamily and sighs.~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",20)
	GlobalLT("#L_GIRomance","GLOBAL",36)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2041) // ~Imoen grins, blushes and can't stifle a giggle.~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",35)
	GlobalLT("#L_GIRomance","GLOBAL",51)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2051) // ~Imoen beams at Garrick, enraptured with his every word.~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",50)
	GlobalLT("#L_GIRomance","GLOBAL",76)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2061) // ~Imoen glows with joy while blowing Garrick a kiss.~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",75)
	GlobalLT("#L_GIRomance","GLOBAL",101)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2071) // ~Imoen beams at Garrick and gives him a wink.~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",100)
	GlobalLT("#L_GIRomance","GLOBAL",126)
	Global("#L_GIMarried","GLOBAL",0)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2082) // ~Imoen blushes and beams with joy.~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",100)
	GlobalLT("#L_GIRomance","GLOBAL",126)
	Global("#L_GIMarried","GLOBAL",1)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2083) // ~Imoen giggles and sings along.~
		EndCutSceneMode()
END

IF
	GlobalGT("#L_GIRomance","GLOBAL",125)
THEN
	RESPONSE #100
		CutSceneId(Player1)
		Wait(2)
		DisplayStringHead("%IMOEN_DV%",@2092) // ~Imoen brushes away a tear of joy.~
		EndCutSceneMode()
END
