///////////////////////////////////////////
// Adds Garrick and Imoen romance to SoD //
///////////////////////////////////////////

DEFINE_ACTION_FUNCTION garroen_sod BEGIN
	// Globals, timers, and kicks off scenes when idle
	ACTION_IF NOT (MOD_IS_INSTALLED ~garroen.tp2~ (ID_OF_LABEL "garroen.tp2" "#L-GARROEN-BG1")) BEGIN
		EXTEND_TOP ~BALDUR.BCS~ ~%mod_root%/scripts/baldur_common.baf~ EVAL
	END
	EXTEND_TOP ~BALDUR.BCS~ ~%mod_root%/scripts/baldur_sod.baf~ EVAL
END